#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, PartialEq)]
pub struct C2PAProvenanceResult {
    /// Whether a supported OpenAI C2PA provenance signal was detected.
    /// If `not_detected`, it means the tool did not find supported signals in the uploaded file. The
    /// content could still have been generated by OpenAI if the metadata was stripped or has evidence of
    /// tampering, the watermark was degraded, it comes from a legacy generation model, or it was created
    /// before provenance signals were available. Content could also still be AI-generated by another
    /// company's model, which the tool currently does not detect.
    pub outcome: ProvenanceDetectionResultApi,
    /// The validation status of the C2PA manifest in the uploaded image.
    pub validation_state: C2PAValidationStateApi,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub issuer: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub generated_at: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, PartialEq)]
pub enum C2PAValidationStateApi {
    #[serde(rename = "trusted")]
    Trusted,
    #[serde(rename = "valid")]
    Valid,
    #[serde(rename = "invalid")]
    Invalid,
    #[serde(rename = "not_present")]
    NotPresent,
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CreateContentProvenanceBody {
    /// The image or audio file to check for supported OpenAI provenance signals.
    pub file: crate::types::InputSource,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, PartialEq)]
pub enum ProvenanceDetectionResultApi {
    #[serde(rename = "detected")]
    Detected,
    #[serde(rename = "not_detected")]
    NotDetected,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, PartialEq)]
pub struct ProvenanceResource {
    /// The object type. Always `content_provenance_check` for this endpoint.
    pub object: String,
    /// The Unix timestamp, in seconds, when the provenance check was created.
    pub created_at: u64,
    /// The provenance results that apply to the uploaded file. Image results include C2PA and SynthID;
    /// audio results include SynthID.
    pub results: Vec<ProvenanceResourceResultsItem>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, PartialEq)]
#[serde(tag = "type")]
pub enum ProvenanceResourceResultsItem {
    #[serde(rename = "c2pa")]
    C2PA(Box<C2PAProvenanceResult>),
    #[serde(rename = "synthid")]
    SynthID(Box<SynthIDProvenanceResult>),
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, PartialEq)]
pub struct SynthIDProvenanceResult {
    /// Whether a supported OpenAI SynthID watermark was detected.
    /// If `not_detected`, it means the tool did not find supported signals in the uploaded file. The
    /// content could still have been generated by OpenAI if the metadata was stripped or has evidence of
    /// tampering, the watermark was degraded, it comes from a legacy generation model, or it was created
    /// before provenance signals were available. Content could also still be AI-generated by another
    /// company's model, which the tool currently does not detect.
    pub outcome: ProvenanceDetectionResultApi,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub generated_at: Option<String>,
}
