[package]
name = "chat-audio"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-openai = {path = "../../async-openai"}
base64 = "0.22.1"
serde_json = "1.0.117"
tokio = { version = "1.38.0", features = ["full"] }
