[package]
name = "structured-outputs-schemars"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-openai = {path = "../../async-openai"}
serde_json = "1.0.127"
tokio = { version = "1.39.3", features = ["full"] }
schemars = "0.8.21"
serde = "1.0.130"
