[package]
name = "web-search"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true
publish = false

[dependencies]
async-openai = { path = "../../async-openai", features = ["byot"] }
futures = "0.3.31"
serde_json = "1.0.135"
tokio = { version = "1.43.0", features = ["full"] }
