[package]
name = "structured-outputs"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-openai = {path = "../../async-openai"}
serde_json = "1.0.127"
tokio = { version = "1.39.3", features = ["full"] }
