[package]
name = "dotenv-client"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-openai = {path = "../../async-openai"}
tokio = { version = "1.25.0", features = ["full"] }
dotenv = "0.15.0"